version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tushar
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: bms_api
    build: .
    image: quotes-api
    command: sh -c "npx prisma generate && npm start"
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: tushar
      DB_NAME: bookMyShow
      DATABASE_URL: "postgresql://postgres:itsTusharHere@database-2.cwzx82bl8rer.us-east-1.rds.amazonaws.com:5432/bookMyShow?schema=public"
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local